spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/mybatis
    username: sa
    password:

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
